export const Dummydata=[
    {
        "name": "Grilled Chicken Breast",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Baked Salmon",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Roasted Turkey Breast",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Tofu Stir-Fry",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Shrimp Scampi",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Pork Tenderloin",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Beef Sirloin",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Egg White Omelet",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Quinoa Salad",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Lentil Soup",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Chicken Caesar Salad",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Veggie Burger",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Stuffed Bell Peppers",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Chicken Stir-Fry",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Grilled Tilapia",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Chickpea Salad",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Baked Cod",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Vegetable Soup",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Thai Chicken Salad",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Beef Taco Salad",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Spinach and Feta Omelet",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Mediterranean Quinoa Bowl",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Sweet Potato and Black Bean Salad",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    },
    {
        "name": "Vegetable Stir-Fry",
        "Calories": "165 kcal",
        "Protein": "31 g",
        "Total Fat": "3.6 g",
        "Saturated Fat": "1 g",
        "Monounsaturated Fat": "1.2 g",
        "Polyunsaturated Fat": "0.8 g",
        "Cholesterol": "85 mg",
        "Sodium": "74 mg",
        "Potassium": "256 mg"
    }
]
